### ISSUE TITLE
Would you consider licensing this?

### ISSUE THREAD

**Issue by christianromney** [stuartsierra/component.pedestal#1]
There's some really useful code here. I've written similar code several times, but there are some nice improvements in your version. For instance, I hit on the idea of exposing the Pedestal component's dependencies, but I added all of them to the request map using the keys they had on the Pedestal component. I like your way better. Even if you don't want to take on maintenance of a whole new library, an open license would allow others to copy and modify. :) 

 I had prematurely dismissed the idea of exposing the entire Pedestal component, but after reading through your component, I think it's actually much cleaner to do so. One thing I still do is split the servlet and server into two independent components. This allows me to remove the http server from the test-system prior to component/start. 

I'd be very interested to read any thoughts you might like to share on the patterns and practices you are happy with and those you're not yet satisfied with regarding the Pedestal/Component combo. I know you talked to Dan (@ddeaguiar) about some of this stuff, but I hope you'll indulge my desire to hear from you directly. 

Cheers.
Christian

**Comment by stuartsierra** [comment]
License file added in https://github.com/stuartsierra/component.pedestal/commit/2f9b434cdaa31021761bab1e77372008be5e7511
